### ISSUE TITLE
Manifest application/vnd.oci.image.manifest.v1+json

### ISSUE THREAD

**Issue by hhergeth** [chickenbellyfin/registry-ui#3]
I use podman/buildah to create images which I push to a private instance of the [Docker registry](https://hub.docker.com/_/registry).

I tried using this nice UI but ran into a problem immediately because the images that podman creates have
`"ManifestType": "application/vnd.oci.image.manifest.v1+json"`
while images from Docker (for example the one for this UI) have
`"ManifestType": "application/vnd.docker.distribution.manifest.v2+json"`

After some quick hackery (replacing the Accept Header in api.py) I was able to use the ui with my images without any problems which leads me to believe that the two manifest types must be similar enough.

I am not terribly familiar with these low level image aspects and was wondering what a proper solution would be. Do I need to build my images differently or can the UI just show both types without problems?

**Comment by chickenbellyfin** [comment]
I wonder if its possible to add the OCI header to the header instead of replacing `application/vnd.docker.distribution.manifest.v2+json,application/vnd.docker.distribution.manifest.list.v2+json,application/vnd.oci.image.manifest.v1+json`? Feel free to open a pull request for it. To test it you probably just need a registry with both podman and docker build images and make sure they both work.
